import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getSupabaseArticles, getSupabaseBrandBySlug, getSupabaseSettings } from '@/lib/supabase-db';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { Tag } from 'lucide-react';
import { getLanguageByCode, SUPPORTED_LANGUAGES } from '@/lib/languages';

interface LangBrandPageProps { params: Promise<{ lang: string; slug: string }> }
export const dynamic = 'force-dynamic';
export async function generateMetadata({params}:LangBrandPageProps){const {lang,slug}=await params;const brand=await getSupabaseBrandBySlug(slug);const langObj=getLanguageByCode(lang);if(!brand)return{title:'Brand Not Found - ErrorCodeWiki'};const settings=await getSupabaseSettings();const siteUrl=settings.siteUrl||'https://errorcodewiki.org';const languages:Record<string,string>={};SUPPORTED_LANGUAGES.forEach(l=>{languages[l.code]=l.code==='en'?`${siteUrl}/brand/${slug}`:`${siteUrl}/${l.code}/brand/${slug}`});return{title:`${brand.name} Error Codes & Diagnostics - ${langObj.name}`,description:brand.description||`Database of error codes, fault messages, and solutions for ${brand.name} equipment in ${langObj.name}.`,alternates:{canonical:`${siteUrl}/${lang}/brand/${slug}`,languages}};}
export default async function LangBrandPage({params}:LangBrandPageProps){const {lang,slug}=await params;const brand=await getSupabaseBrandBySlug(slug);const langObj=getLanguageByCode(lang);if(!brand)notFound();const {articles,total}=await getSupabaseArticles({status:'published',brandSlug:slug,language:lang});return <div className="min-h-screen bg-white text-gray-900 font-sans flex flex-col"><Navbar/><main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 pt-4"><Breadcrumbs items={[{label:'Brands',href:`/${lang}`},{label:`${brand.name} (${langObj.flag} ${langObj.code.toUpperCase()})`}]}/><div className="my-4 pb-4 border-b border-gray-300 bg-[#f8f9fa] p-6 rounded-xs"><div className="flex items-center gap-3 mb-2"><div className="p-2 bg-blue-900 text-white rounded-xs"><Tag className="w-5 h-5"/></div><div><h1 className="font-serif text-2xl font-bold">{brand.name} Fault Code Manuals ({langObj.name})</h1><p className="text-xs text-gray-600 font-mono mt-0.5">{total} Documented {brand.name} Errors</p></div></div><p className="text-xs text-gray-700 max-w-3xl">{brand.description}</p><div className="mt-3 text-xs text-gray-600 font-mono"><strong>Supported Device Hardware:</strong> {brand.deviceTypes.join(', ')}</div></div><div className="my-6 space-y-4"><h2 className="font-serif text-lg font-bold border-b border-gray-200 pb-2">{brand.name} Articles &amp; Diagnostic Guides ({langObj.name})</h2>{articles.length===0?<div className="p-8 text-center bg-gray-50 border border-gray-200 text-xs text-gray-600">No error codes listed under {brand.name} yet.</div>:<div className="divide-y divide-gray-200 border border-gray-300 bg-white rounded-xs">{articles.map(art=>{const targetUrl=art.language==='en'?`/error/${art.slug}`:`/${art.language||lang}/error/${art.slug}`;return <article key={art.id} className="p-4 hover:bg-gray-50"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 mb-1"><span className="font-mono text-xs font-bold px-2 py-0.5 bg-blue-900 text-white rounded-xs">{art.errorCode}</span><span className="text-xs text-gray-500 font-mono">{art.deviceType}</span></div><h3 className="font-serif font-bold text-base hover:text-blue-700"><Link href={targetUrl}>{art.title}</Link></h3><p className="text-xs text-gray-600 mt-1 line-clamp-2">{art.shortDefinition}</p></div><Link href={targetUrl} className="shrink-0 px-3 py-1.5 border border-gray-300 text-xs hover:bg-gray-100 rounded-xs">Read Fix</Link></div></article>})}</div>}</div></main><Footer/></div>}
