import { Metadata } from 'next';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { Footer } from '@/components/Footer';
import { Navbar } from '@/components/Navbar';
import { ShieldCheck, Lock, Eye, FileText, Database, Server } from 'lucide-react';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Privacy Policy | ErrorCodeWiki Technical Diagnostic Database', description: 'Privacy Policy for ErrorCodeWiki covering anonymous analytics, advertising, cookies and data rights.' };

export default function PrivacyPolicyPage() {
  const lastUpdated = 'August 23, 2026';
  return <div className="min-h-screen bg-white text-gray-900 font-sans flex flex-col"><Navbar /><main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex-1"><Breadcrumbs items={[{ label: 'Privacy Policy' }]} /><article className="prose prose-gray max-w-none space-y-8">
    <div className="border-b border-gray-300 pb-6"><div className="flex items-center gap-2 text-blue-700 text-xs font-mono font-bold uppercase tracking-wider mb-2"><ShieldCheck className="w-4 h-4" /><span>Legal &amp; Privacy Compliance</span></div><h1 className="font-serif text-3xl sm:text-4xl font-bold text-gray-900 tracking-tight">Privacy Policy</h1><p className="text-gray-600 text-sm mt-2">Effective Date: <time dateTime="2026-08-23">{lastUpdated}</time></p></div>
    <div className="bg-blue-50 border border-blue-200 p-4 rounded-xs text-xs text-blue-900 space-y-2"><div className="font-bold flex items-center gap-1.5 text-sm text-blue-950"><Lock className="w-4 h-4 text-blue-700" />Privacy Overview</div><p className="leading-relaxed">ErrorCodeWiki does not require an account to read public manuals. We use anonymous first-party analytics to understand traffic sources, countries, devices and page usage. Advertising is optional and is only loaded when the site has valid ad configuration.</p></div>
    <section className="space-y-3"><h2 className="font-serif text-xl font-bold border-b border-gray-200 pb-1 flex items-center gap-2"><Eye className="w-5 h-5" />1. Anonymous Analytics</h2><p className="text-sm text-gray-700 leading-relaxed">Our first-party analytics records an anonymous session identifier, page path, landing page, referring hostname, campaign parameters, approximate country/region supplied by the hosting platform, device type, browser, operating system, screen dimensions, language and page title. We do not store the visitor&apos;s IP address. A Do Not Track browser signal disables our client-side analytics collection.</p><p className="text-sm text-gray-700 leading-relaxed">Search keywords are recorded only when a search engine exposes a query in the referring URL. Google commonly removes organic query terms from referrers; we do not infer or guess missing Google keywords.</p></section>
    <section className="space-y-3"><h2 className="font-serif text-xl font-bold border-b border-gray-200 pb-1 flex items-center gap-2"><Database className="w-5 h-5" />2. Advertising</h2><p className="text-sm text-gray-700 leading-relaxed">The site may use Google AdSense. When enabled, Google and its partners may use cookies or similar technologies according to their own policies. Ads are placed in responsive top, in-content, desktop sidebar, bottom and mobile-sticky slots. The site does not send analytics event data to the ad system.</p></section>
    <section className="space-y-3"><h2 className="font-serif text-xl font-bold border-b border-gray-200 pb-1 flex items-center gap-2"><Server className="w-5 h-5" />3. Security &amp; Retention</h2><p className="text-sm text-gray-700 leading-relaxed">Analytics data is stored in our Supabase database and is accessible only to authorized server-side administration. Secrets such as database service keys, admin passwords and ad credentials are never stored in browser storage or analytics records.</p></section>
    <section className="space-y-3"><h2 className="font-serif text-xl font-bold border-b border-gray-200 pb-1 flex items-center gap-2"><FileText className="w-5 h-5" />4. Your Rights</h2><p className="text-sm text-gray-700 leading-relaxed">Depending on your jurisdiction, you may have rights to access, correct or delete personal data. Because our analytics is designed to be anonymous and does not store IP addresses, individual identification may not be possible from an analytics session alone.</p></section>
  </article></main><Footer /></div>;
}
