'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { AlertTriangle, Check, ChevronDown, LockKeyhole, ShieldCheck } from 'lucide-react';
import { CalculatorDefinition } from '@/data/calculators';

interface DebtRow { id: number; balance: number; apr: number; payment: number }

const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(Number.isFinite(n) ? n : 0);
const pct = (n: number) => `${Number.isFinite(n) ? n.toFixed(1) : '0.0'}%`;
const monthlyPayment = (principal: number, annualRate: number, months: number) => {
  const r = annualRate / 100 / 12;
  if (months <= 0 || principal <= 0) return 0;
  return r === 0 ? principal / months : principal * r * Math.pow(1 + r, months) / (Math.pow(1 + r, months) - 1);
};

function Input({ label, id, value, onChange, min = 0, max = 1000000, step = 1, prefix, suffix }: { label: string; id: string; value: number; onChange: (n: number) => void; min?: number; max?: number; step?: number; prefix?: string; suffix?: string }) {
  return <div className="space-y-2"><label htmlFor={id} className="block text-sm font-semibold text-gray-800">{label}</label><div className="flex items-center rounded-lg border border-gray-300 bg-white focus-within:ring-2 focus-within:ring-blue-600"><span className="pl-3 text-gray-500">{prefix}</span><input id={id} aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e => onChange(Math.min(max, Math.max(min, Number(e.target.value) || 0)))} className="w-full rounded-lg border-0 bg-transparent px-2 py-2.5 outline-none focus:ring-0" />{suffix && <span className="pr-3 text-gray-500">{suffix}</span>}</div><input aria-label={`${label} slider`} type="range" min={min} max={max} step={step} value={value} onChange={e => onChange(Number(e.target.value))} className="w-full accent-blue-700" /></div>;
}

function Card({ title, value, note }: { title: string; value: string; note?: string }) { return <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="text-xs font-semibold uppercase tracking-wide text-gray-500">{title}</div><div className="mt-1 text-2xl font-bold text-gray-950">{value}</div>{note && <div className="mt-1 text-xs text-gray-500">{note}</div>}</div>; }

export function CalculatorPage({ calculator }: { calculator: CalculatorDefinition }) {
  const [balance, setBalance] = useState(5000); const [apr, setApr] = useState(24); const [minimumPct, setMinimumPct] = useState(2); const [income, setIncome] = useState(8000); const [housing, setHousing] = useState(2000); const [otherDebt, setOtherDebt] = useState(800); const [loanApr, setLoanApr] = useState(14); const [term, setTerm] = useState(48); const [extra, setExtra] = useState(250);
  const [debts, setDebts] = useState<DebtRow[]>([{ id: 1, balance: 5000, apr: 24, payment: 150 }, { id: 2, balance: 1500, apr: 12, payment: 75 }]);
  const updateDebt = (id: number, key: keyof Omit<DebtRow, 'id'>, value: number) => setDebts(rows => rows.map(d => d.id === id ? { ...d, [key]: value } : d));
  const addDebt = () => setDebts(rows => rows.length >= 8 ? rows : [...rows, { id: Date.now(), balance: 1000, apr: 18, payment: 50 }]);

  const result = useMemo(() => {
    if (calculator.slug === 'credit-card-calculator') {
      const fixed = monthlyPayment(balance, apr, 36); const minFirst = Math.max(balance * minimumPct / 100, 25); const firstInterest = balance * apr / 100 / 12; const minPrincipal = Math.max(0, minFirst - firstInterest);
      const minMonthsEstimate = minPrincipal > 0 ? Math.ceil(Math.log((minFirst) / (minFirst - balance * apr / 100 / 12)) / Math.log(1 + apr / 100 / 12)) : 999;
      return { cards: [<Card key="fixed" title="36-month payment" value={money(fixed)} note="No new charges" />, <Card key="min" title="First minimum" value={money(minFirst)} note="Issuer rules vary" />, <Card key="interest" title="First-month interest" value={money(firstInterest)} />], primary: money(fixed), secondary: `Minimum-payment estimate: ${minMonthsEstimate > 900 ? 'very long' : `${minMonthsEstimate} months`}`, warning: minimumPct <= 2.5 && apr >= 20 ? 'High APR + low minimum can prolong repayment.' : undefined };
    }
    if (calculator.slug === 'credit-cards-payoff-calculator') {
      const total = debts.reduce((s, d) => s + d.balance, 0); const interest = debts.reduce((s, d) => s + d.balance * d.apr / 100 / 12, 0); const weighted = total ? debts.reduce((s, d) => s + d.balance * d.apr, 0) / total : 0;
      return { cards: [<Card key="balance" title="Total balance" value={money(total)} />, <Card key="interest" title="Est. monthly interest" value={money(interest)} />, <Card key="apr" title="Weighted APR" value={pct(weighted)} />], primary: money(total), secondary: `${debts.length} cards modeled`, warning: weighted >= 25 ? 'Weighted APR is high; prioritize high-rate balances.' : undefined };
    }
    if (calculator.slug === 'debt-payoff-calculator') {
      const total = debts.reduce((s, d) => s + d.balance, 0); const avalanche = [...debts].sort((a, b) => b.apr - a.apr); const snowball = [...debts].sort((a, b) => a.balance - b.balance); const totalMin = debts.reduce((s, d) => s + d.payment, 0); const annualInterest = debts.reduce((s, d) => s + d.balance * d.apr / 100, 0);
      return { cards: [<Card key="av" title="Avalanche target" value={money(avalanche[0]?.balance ?? 0)} note={`${pct(avalanche[0]?.apr ?? 0)} APR`} />, <Card key="sn" title="Snowball target" value={money(snowball[0]?.balance ?? 0)} />, <Card key="budget" title="Monthly payoff budget" value={money(totalMin + extra)} />], primary: annualInterest > 0 ? money(annualInterest / 12) : money(0), secondary: 'Estimated monthly interest before payments', warning: totalMin + extra <= 0 ? 'Add a monthly payment budget.' : undefined };
    }
    if (calculator.slug === 'debt-consolidation-calculator') {
      const total = debts.reduce((s, d) => s + d.balance, 0); const weighted = total ? debts.reduce((s, d) => s + d.balance * d.apr, 0) / total : 0; const payment = monthlyPayment(total, loanApr, term); const interest = payment * term - total;
      return { cards: [<Card key="current" title="Weighted current APR" value={pct(weighted)} />, <Card key="new" title="Consolidation APR" value={pct(loanApr)} />, <Card key="payment" title="New monthly payment" value={money(payment)} />], primary: pct(weighted - loanApr), secondary: `Rate difference: ${pct(weighted - loanApr)}; estimated interest ${money(interest)}`, warning: loanApr >= weighted ? 'The consolidation rate is not below the current weighted APR.' : undefined };
    }
    const front = income ? housing / income * 100 : 0; const back = income ? (housing + otherDebt) / income * 100 : 0; const score = back <= 36 ? 'Lower' : back <= 43 ? 'Moderate' : back <= 50 ? 'Elevated' : 'High';
    return { cards: [<Card key="front" title="Front-end DTI" value={pct(front)} note="Housing / gross income" />, <Card key="back" title="Back-end DTI" value={pct(back)} note="Total recurring debt" />, <Card key="score" title="Planning risk" value={score} />], primary: pct(back), secondary: `Housing share: ${pct(front)}`, warning: back > 43 ? 'Verify current lender and program-specific DTI requirements.' : undefined };
  }, [calculator.slug, balance, apr, minimumPct, income, housing, otherDebt, loanApr, term, extra, debts]);

  const isCards = calculator.slug === 'credit-cards-payoff-calculator' || calculator.slug === 'debt-payoff-calculator' || calculator.slug === 'debt-consolidation-calculator';
  const related = calculator.related.map(slug => <Link key={slug} href={`/calculator/${slug}`} className="rounded-lg border border-gray-200 p-3 text-sm font-semibold hover:border-blue-500 hover:bg-blue-50">{slug.replaceAll('-', ' ')}</Link>);
  const jsonLd = JSON.stringify([{ '@context': 'https://schema.org', '@type': 'WebApplication', name: calculator.title, applicationCategory: 'FinanceApplication', operatingSystem: 'Any', description: calculator.description }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: calculator.faqs.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }, { '@context': 'https://schema.org', '@type': 'HowTo', name: `How to use ${calculator.title}`, step: calculator.howTo.map((text, i) => ({ '@type': 'HowToStep', position: i + 1, text })) }, { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Calculators', item: '/calculator' }, { '@type': 'ListItem', position: 2, name: calculator.title, item: `/calculator/${calculator.slug}` }] }]);

  return <main className="mx-auto max-w-6xl px-4 py-8"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd }} />
    <header className="mb-8"><div className="flex flex-wrap items-center gap-2"><span className="text-3xl" aria-hidden="true">{calculator.icon}</span><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">{calculator.category}</span></div><h1 className="mt-3 text-3xl font-extrabold tracking-tight">{calculator.title}</h1><p className="mt-2 max-w-3xl text-gray-700">{calculator.description} <strong>{calculator.rule}</strong></p></header>
    <section className="grid gap-6 lg:grid-cols-2" aria-label="Calculator widget"><div className="rounded-2xl border border-gray-200 bg-gray-50 p-5 shadow-sm"><h2 className="text-xl font-bold">Inputs</h2><p className="mb-5 mt-1 text-xs text-gray-600">Results computed instantly — your data never leaves your device.</p>
      {calculator.slug === 'credit-card-calculator' && <div className="space-y-5"><Input label="Card balance" id="card-balance" value={balance} onChange={setBalance} max={100000} prefix="$" /><Input label="APR" id="card-apr" value={apr} onChange={setApr} max={60} step={0.1} suffix="%" /><Input label="Minimum payment percentage" id="minimum-payment" value={minimumPct} onChange={setMinimumPct} min={1} max={10} step={0.1} suffix="%" /></div>}
      {calculator.slug === 'debt-to-income-ratio-calculator' && <div className="space-y-5"><Input label="Gross monthly income" id="gross-income" value={income} onChange={setIncome} max={100000} prefix="$" /><Input label="Monthly housing costs" id="housing" value={housing} onChange={setHousing} max={50000} prefix="$" /><Input label="Other monthly debt" id="other-debt" value={otherDebt} onChange={setOtherDebt} max={50000} prefix="$" /></div>}
      {calculator.slug === 'debt-consolidation-calculator' && <div className="space-y-5"><p className="text-sm font-semibold">Existing debts</p>{debts.map(d => <div key={d.id} className="grid gap-3 rounded-lg border bg-white p-3 sm:grid-cols-3"><Input label={`Balance #${d.id}`} id={`balance-${d.id}`} value={d.balance} onChange={v => updateDebt(d.id, 'balance', v)} max={100000} prefix="$" /><Input label="APR" id={`apr-${d.id}`} value={d.apr} onChange={v => updateDebt(d.id, 'apr', v)} max={60} step={0.1} suffix="%" /><Input label="Minimum" id={`payment-${d.id}`} value={d.payment} onChange={v => updateDebt(d.id, 'payment', v)} max={10000} prefix="$" /></div>)}<button onClick={addDebt} className="rounded-lg border px-4 py-2 text-sm font-bold hover:bg-white" disabled={debts.length >= 8}>+ Add debt</button><Input label="Consolidation APR" id="loan-apr" value={loanApr} onChange={setLoanApr} max={60} step={0.1} suffix="%" /><Input label="Loan term" id="loan-term" value={term} onChange={setTerm} min={6} max={120} suffix="months" /></div>}
      {(calculator.slug === 'credit-cards-payoff-calculator' || calculator.slug === 'debt-payoff-calculator') && <div className="space-y-4"><p className="text-sm font-semibold">Debts</p>{debts.map(d => <div key={d.id} className="grid gap-3 rounded-lg border bg-white p-3 sm:grid-cols-3"><Input label={`Balance #${d.id}`} id={`debt-balance-${d.id}`} value={d.balance} onChange={v => updateDebt(d.id, 'balance', v)} max={100000} prefix="$" /><Input label="APR" id={`debt-apr-${d.id}`} value={d.apr} onChange={v => updateDebt(d.id, 'apr', v)} max={60} step={0.1} suffix="%" /><Input label="Minimum" id={`debt-payment-${d.id}`} value={d.payment} onChange={v => updateDebt(d.id, 'payment', v)} max={10000} prefix="$" /></div>)}<button onClick={addDebt} className="rounded-lg border px-4 py-2 text-sm font-bold hover:bg-white" disabled={debts.length >= 8}>+ Add debt</button>{calculator.slug === 'debt-payoff-calculator' && <Input label="Extra monthly payoff" id="extra-payment" value={extra} onChange={setExtra} max={10000} prefix="$" />}</div>}
    </div><div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Results</h2><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-bold text-green-700"><ShieldCheck className="mr-1 inline h-4 w-4" />100% Client-Side - Private & Secure</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{result.cards}</div><div className="mt-5 rounded-xl bg-gray-50 p-4"><div className="text-xs uppercase text-gray-500">Primary metric</div><div className="text-3xl font-extrabold">{result.primary}</div><div className="mt-1 text-sm text-gray-600">{result.secondary}</div></div><div className="mt-4"><div className="mb-1 flex justify-between text-xs"><span>Progress / risk indicator</span><span>{result.primary}</span></div><div className="h-3 overflow-hidden rounded-full bg-gray-200"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, Math.max(0, Number.parseFloat(result.primary) || 0))}%` }} /></div></div>{result.warning && <div role="alert" className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle className="mr-2 inline h-4 w-4" />{result.warning}</div>}<div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs">Instant recalculation</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs">No server calculation</span></div></div></section>
    <section className="mt-12"><h2 className="text-2xl font-bold">How to Use</h2><ol className="mt-4 grid gap-3 md:grid-cols-4">{calculator.howTo.map((s, i) => <li key={s} className="rounded-xl border p-4"><span className="text-lg font-extrabold text-blue-700">{i + 1}</span><p className="mt-2 text-sm">{s}</p></li>)}</ol></section>
    <section className="mt-12 grid gap-6 md:grid-cols-2"><div><h2 className="text-2xl font-bold">Formula & Mathematical Basis</h2><div className="mt-4 rounded-xl bg-gray-950 p-5 font-mono text-sm text-white">{calculator.formula}</div><dl className="mt-4 space-y-2">{calculator.variables.map(([k, v]) => <div key={k} className="flex gap-3"><dt className="w-24 font-bold">{k}</dt><dd className="text-gray-700">{v}</dd></div>)}</dl></div><div className="rounded-xl border-l-4 border-blue-600 bg-blue-50 p-5"><h3 className="font-bold">Technical Math Callout</h3><p className="mt-2 text-sm leading-6">{calculator.mathCallout}</p></div></section>
    <section className="mt-12"><h2 className="text-2xl font-bold">Step-by-Step Example</h2><div className="mt-4 rounded-xl border bg-gray-50 p-5"><p className="font-semibold">{calculator.example.scenario}</p><ol className="mt-3 list-decimal space-y-2 pl-5">{calculator.example.steps.map(s => <li key={s}>{s}</li>)}</ol><div className="mt-4 rounded-lg bg-green-50 p-4 font-bold text-green-800"><Check className="mr-2 inline h-5 w-5" />Final Output: {calculator.example.output}</div></div></section>
    <section className="mt-12 grid gap-6 md:grid-cols-2"><div><h2 className="text-2xl font-bold">Practical Use Cases</h2><ul className="mt-4 space-y-2">{calculator.useCases.map(x => <li key={x}>✓ {x}</li>)}</ul><h2 className="mt-8 text-2xl font-bold">Common Mistakes to Avoid</h2><ul className="mt-4 space-y-2">{calculator.mistakes.map(x => <li key={x}>⚠ {x}</li>)}</ul></div><div><h2 className="text-2xl font-bold">Glossary</h2><dl className="mt-4 space-y-3">{calculator.glossary.map(([term, definition]) => <div key={term}><dt className="font-bold">{term}</dt><dd className="text-sm text-gray-700">{definition}</dd></div>)}</dl></div></section>
    <section className="mt-12"><h2 className="text-2xl font-bold">FAQ</h2><div className="mt-4 space-y-2">{calculator.faqs.map((f, i) => <details key={f.question} open={i === 0} className="group rounded-xl border p-4"><summary className="cursor-pointer list-none font-bold">{f.question}<ChevronDown className="float-right h-5 w-5 transition group-open:rotate-180" /></summary><p className="mt-3 text-sm leading-6 text-gray-700">{f.answer}</p></details>)}</div></section>
    <section className="mt-12 rounded-xl border bg-gray-50 p-5"><h2 className="text-xl font-bold">Sources & EEAT References</h2><ul className="mt-3 space-y-2 text-sm">{calculator.sources.map(s => <li key={s.name}><strong>{s.name}:</strong> {s.note}</li>)}</ul><div className="mt-5 flex items-center gap-2 text-sm font-semibold"><LockKeyhole className="h-4 w-4" />CalculatorFree Editorial Team · Checked against standard consumer-finance concepts</div></section>
    <section className="mt-12"><h2 className="text-2xl font-bold">Related Calculators</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{related}</div></section>
  </main>;
}
